//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        public int ID { get; set; }
        public string YemekAdi { get; set; }
        public string AraSicakAdi { get; set; }
        public string İcecekeler { get; set; }
    }
}
